// flow-typed signature: b743f70f9c102092f270d40cc6c5cffe
// flow-typed version: <<STUB>>/neon-cli_v^0.1.13/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neon-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'neon-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neon-cli/bin/cli' {
  declare module.exports: any;
}

declare module 'neon-cli/lib/async/child_process' {
  declare module.exports: any;
}

declare module 'neon-cli/lib/async/fs' {
  declare module.exports: any;
}

declare module 'neon-cli/lib/async/git-config' {
  declare module.exports: any;
}

declare module 'neon-cli/lib/async/inquirer' {
  declare module.exports: any;
}

declare module 'neon-cli/lib/cli' {
  declare module.exports: any;
}

declare module 'neon-cli/lib/index' {
  declare module.exports: any;
}

declare module 'neon-cli/lib/ops/neon_build' {
  declare module.exports: any;
}

declare module 'neon-cli/lib/ops/neon_new' {
  declare module.exports: any;
}

declare module 'neon-cli/lib/ops/style' {
  declare module.exports: any;
}

declare module 'neon-cli/src/async/child_process' {
  declare module.exports: any;
}

declare module 'neon-cli/src/async/fs' {
  declare module.exports: any;
}

declare module 'neon-cli/src/async/git-config' {
  declare module.exports: any;
}

declare module 'neon-cli/src/async/inquirer' {
  declare module.exports: any;
}

declare module 'neon-cli/src/cli' {
  declare module.exports: any;
}

declare module 'neon-cli/src/index' {
  declare module.exports: any;
}

declare module 'neon-cli/src/ops/neon_build' {
  declare module.exports: any;
}

declare module 'neon-cli/src/ops/neon_new' {
  declare module.exports: any;
}

declare module 'neon-cli/src/ops/style' {
  declare module.exports: any;
}

declare module 'neon-cli/test/acceptance/help' {
  declare module.exports: any;
}

declare module 'neon-cli/test/acceptance/new' {
  declare module.exports: any;
}

declare module 'neon-cli/test/acceptance/version' {
  declare module.exports: any;
}

declare module 'neon-cli/test/support/acceptance' {
  declare module.exports: any;
}

declare module 'neon-cli/test/support/fs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neon-cli/bin/cli.js' {
  declare module.exports: $Exports<'neon-cli/bin/cli'>;
}
declare module 'neon-cli/lib/async/child_process.js' {
  declare module.exports: $Exports<'neon-cli/lib/async/child_process'>;
}
declare module 'neon-cli/lib/async/fs.js' {
  declare module.exports: $Exports<'neon-cli/lib/async/fs'>;
}
declare module 'neon-cli/lib/async/git-config.js' {
  declare module.exports: $Exports<'neon-cli/lib/async/git-config'>;
}
declare module 'neon-cli/lib/async/inquirer.js' {
  declare module.exports: $Exports<'neon-cli/lib/async/inquirer'>;
}
declare module 'neon-cli/lib/cli.js' {
  declare module.exports: $Exports<'neon-cli/lib/cli'>;
}
declare module 'neon-cli/lib/index.js' {
  declare module.exports: $Exports<'neon-cli/lib/index'>;
}
declare module 'neon-cli/lib/ops/neon_build.js' {
  declare module.exports: $Exports<'neon-cli/lib/ops/neon_build'>;
}
declare module 'neon-cli/lib/ops/neon_new.js' {
  declare module.exports: $Exports<'neon-cli/lib/ops/neon_new'>;
}
declare module 'neon-cli/lib/ops/style.js' {
  declare module.exports: $Exports<'neon-cli/lib/ops/style'>;
}
declare module 'neon-cli/src/async/child_process.js' {
  declare module.exports: $Exports<'neon-cli/src/async/child_process'>;
}
declare module 'neon-cli/src/async/fs.js' {
  declare module.exports: $Exports<'neon-cli/src/async/fs'>;
}
declare module 'neon-cli/src/async/git-config.js' {
  declare module.exports: $Exports<'neon-cli/src/async/git-config'>;
}
declare module 'neon-cli/src/async/inquirer.js' {
  declare module.exports: $Exports<'neon-cli/src/async/inquirer'>;
}
declare module 'neon-cli/src/cli.js' {
  declare module.exports: $Exports<'neon-cli/src/cli'>;
}
declare module 'neon-cli/src/index.js' {
  declare module.exports: $Exports<'neon-cli/src/index'>;
}
declare module 'neon-cli/src/ops/neon_build.js' {
  declare module.exports: $Exports<'neon-cli/src/ops/neon_build'>;
}
declare module 'neon-cli/src/ops/neon_new.js' {
  declare module.exports: $Exports<'neon-cli/src/ops/neon_new'>;
}
declare module 'neon-cli/src/ops/style.js' {
  declare module.exports: $Exports<'neon-cli/src/ops/style'>;
}
declare module 'neon-cli/test/acceptance/help.js' {
  declare module.exports: $Exports<'neon-cli/test/acceptance/help'>;
}
declare module 'neon-cli/test/acceptance/new.js' {
  declare module.exports: $Exports<'neon-cli/test/acceptance/new'>;
}
declare module 'neon-cli/test/acceptance/version.js' {
  declare module.exports: $Exports<'neon-cli/test/acceptance/version'>;
}
declare module 'neon-cli/test/support/acceptance.js' {
  declare module.exports: $Exports<'neon-cli/test/support/acceptance'>;
}
declare module 'neon-cli/test/support/fs.js' {
  declare module.exports: $Exports<'neon-cli/test/support/fs'>;
}
